// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using BasicTrelloImplementation.CardJsonTypes;

namespace BasicTrelloImplementation.CardJsonTypes
{

    public class Badges
    {

        [JsonProperty("votes")]
        public int Votes { get; set; }

        [JsonProperty("viewingMemberVoted")]
        public bool ViewingMemberVoted { get; set; }

        [JsonProperty("subscribed")]
        public bool Subscribed { get; set; }

        [JsonProperty("fogbugz")]
        public string Fogbugz { get; set; }

        [JsonProperty("checkItems")]
        public int CheckItems { get; set; }

        [JsonProperty("checkItemsChecked")]
        public int CheckItemsChecked { get; set; }

        [JsonProperty("comments")]
        public int Comments { get; set; }

        [JsonProperty("attachments")]
        public int Attachments { get; set; }

        [JsonProperty("description")]
        public bool Description { get; set; }

        [JsonProperty("due")]
        public object Due { get; set; }

        [JsonProperty("dueComplete")]
        public bool DueComplete { get; set; }
    }

}
