// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using BasicTrelloImplementation.CardJsonTypes;
using Newtonsoft.Json;

namespace BasicTrelloImplementation.Models
{

    public class Card
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

}
