// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using BasicTrelloImplementation.CardJsonTypes;
using Newtonsoft.Json;

namespace BasicTrelloImplementation.Models
{

    public class Card
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        //[JsonProperty("badges")]
        //public Badges Badges { get; set; }

        //[JsonProperty("checkItemStates")]
        //public object[] CheckItemStates { get; set; }

        //[JsonProperty("closed")]
        //public bool Closed { get; set; }

        //[JsonProperty("dueComplete")]
        //public bool DueComplete { get; set; }

        //[JsonProperty("dateLastActivity")]
        //public string DateLastActivity { get; set; }

        //[JsonProperty("desc")]
        //public string Desc { get; set; }

        //[JsonProperty("descData")]
        //public object DescData { get; set; }

        //[JsonProperty("due")]
        //public object Due { get; set; }

        //[JsonProperty("email")]
        //public object Email { get; set; }

        //[JsonProperty("idBoard")]
        //public string IdBoard { get; set; }

        //[JsonProperty("idChecklists")]
        //public object[] IdChecklists { get; set; }

        //[JsonProperty("idList")]
        //public string IdList { get; set; }

        //[JsonProperty("idMembers")]
        //public string[] IdMembers { get; set; }

        //[JsonProperty("idMembersVoted")]
        //public object[] IdMembersVoted { get; set; }

        //[JsonProperty("idShort")]
        //public int IdShort { get; set; }

        //[JsonProperty("idAttachmentCover")]
        //public string IdAttachmentCover { get; set; }

        //[JsonProperty("manualCoverAttachment")]
        //public bool ManualCoverAttachment { get; set; }

        //[JsonProperty("labels")]
        //public Label[] Labels { get; set; }

        //[JsonProperty("idLabels")]
        //public string[] IdLabels { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

    //    [JsonProperty("pos")]
    //    public int Pos { get; set; }

    //    [JsonProperty("shortLink")]
    //    public string ShortLink { get; set; }

    //    [JsonProperty("shortUrl")]
    //    public string ShortUrl { get; set; }

    //    [JsonProperty("subscribed")]
    //    public bool Subscribed { get; set; }

    //    [JsonProperty("url")]
    //    public string Url { get; set; }
    }

}
